name: Notify Slack on Push

on:
  push:
    branches:
      - main  # Runs when code is pushed to main

jobs:
  notify-slack:
    runs-on: ubuntu-latest
    steps:
      - name: Send Message to Slack
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_MESSAGE: "🚀 New code pushed to main branch!"
          SLACK_USERNAME: "GitHub Actions Bot"
