name: Notify Slack on GitHub Events

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, closed]
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  notify-slack:
    runs-on: ubuntu-latest
    steps:
      - name: Send Message to Slack
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_MESSAGE: "🚀 GitHub Action triggered for event: ${{ github.event_name }}"
          SLACK_USERNAME: "GitHub Actions Bot"
